Repository ZeissIQS/zeiss-inspect-addon-api, pull requests merged in 2024-07, with the labels that each got.

#156 Document additional Selection Element widget properties (2023)
  doc/howtos/python_api_introduction/assets/dialog_custom_elem_select.py
  doc/howtos/python_api_introduction/user_defined_dialogs.md
Labels: enhancement, howto

#151 Update localize_triangles.py
  doc/howtos/faq/assets/localize_triangles.py
Labels: bug

#152 Update localize_triangles.py
  doc/howtos/faq/assets/localize_triangles.py
Labels: bug

#154 Updated for SW2025: XLIFF editing, export and import
  doc/howtos/localization/assets/edit_xliff.png
  doc/howtos/localization/assets/export_import_xliff.png
  doc/howtos/localization/localization.md
Labels: update

#157 Added file selection dialog
  doc/howtos/python_api_introduction/assets/choose_file_configuration.png
  doc/howtos/python_api_introduction/assets/choose_file_dialog.png
  doc/howtos/python_api_introduction/assets/configure_file_selection.png
  doc/howtos/python_api_introduction/file_selection_dialog.md
  doc/index.md
Labels: howto
